apiVersion: apps/v1
kind: Deployment
metadata:
  name: order_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order_service
  template:
    metadata:
      labels:
        app: order_service
    spec:
      containers:
      - name: order_service
        image: order_service:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: order_service
spec:
  selector:
    app: order_service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
